name: Github Actions Example

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Octo Organization
